/**
 * Zodiac News (Zodiac Today) – AI-generated blogs listing
 * Same UI as Astrology Blog page; shows only autoGenerated published blogs.
 * Human-written blogs remain on /blog.
 */

import { getPublishedBlogsAutoGenerated } from '@/lib/blog'
import { generateExcerpt, calculateReadTime } from '@/lib/blog-utils'
import { getOptimizedImageUrl } from '@/lib/image-optimize'
import Image from 'next/image'
import { Suspense } from 'react'
import BlogListClient from '@/app/blog/BlogListClient'
import BlogFilters from '@/app/blog/BlogFilters'
import BlogFloatingCTA from '@/app/blog/BlogFloatingCTA'
import BlogTextFixer from '@/app/blog/BlogTextFixer'
import BackButtonHandler from '@/app/blog/BackButtonHandler'
import PageSEO from '@/components/PageSEO'
import '@/app/blog/blog.css'

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || 'https://niraliveastro.com'

export const revalidate = 60

export async function generateMetadata() {
  const blogs = await getPublishedBlogsAutoGenerated()

  return {
    title: 'Zodiac News | Daily Zodiac & Astrology Insights',
    description: 'AI-generated zodiac and astrology articles: daily predictions, planetary transits, and Vedic insights. Fresh zodiac news and cosmic updates.',
    keywords: [
      'zodiac news',
      'zodiac today',
      'daily zodiac',
      'AI astrology',
      'zodiac predictions',
      'astrology insights',
      'planetary transits',
      'vedic astrology news',
    ],
    authors: [{ name: 'NiraLive Astro' }],
    other: { 'font-display': 'block' },
    openGraph: {
      title: 'Zodiac News | Daily Zodiac & Astrology Insights | NiraLive Astro',
      description: 'AI-generated zodiac and astrology articles: daily predictions, planetary transits, and Vedic insights.',
      url: `${SITE_URL}/zodiac-today`,
      siteName: 'NiraLive Astro',
      images: [{ url: `${SITE_URL}/og-image.png`, width: 1200, height: 630, alt: 'NiraLive Astro Zodiac News' }],
      locale: 'en_US',
      type: 'website',
    },
    twitter: {
      card: 'summary_large_image',
      title: 'Zodiac News | Daily Zodiac & Astrology Insights',
      description: 'AI-generated zodiac and astrology articles: daily predictions and cosmic updates.',
      images: [`${SITE_URL}/og-image.png`],
      creator: '@niraliveastro',
    },
    alternates: {
      canonical: `${SITE_URL}/zodiac-today`,
    },
  }
}

// Category mapping (same as blog page / BlogFilters)
function mapTagToCategory(tag) {
  const normalizedTag = tag.toLowerCase().trim()
  const primaryCategories = [
    'Love & Relationships',
    'Marriage & Match Making',
    'Career & Job',
    'Business & Money',
    'Health & Well-Being',
    'Sleep & Mental Peace',
    'Home & Vastu',
    'Spiritual Growth',
    'Daily / Monthly Predictions',
  ]
  const secondaryCategories = [
    'Astrology Basics',
    'Planets & Grahas',
    'Houses (Bhavas)',
    'Yogas & Doshas',
    'Remedies & Upay',
    'Dasha & Transits',
    'Muhurat & Auspicious Time',
    'Panchang',
    'Festivals & Rituals',
    'Yearly Forecasts',
  ]
  for (const category of primaryCategories) {
    const catNormalized = category.toLowerCase().replace(/[&/]/g, '').replace(/\s+/g, '')
    if (normalizedTag.includes(catNormalized) || catNormalized.includes(normalizedTag)) {
      return category.toLowerCase().trim()
    }
  }
  for (const category of secondaryCategories) {
    const catNormalized = category.toLowerCase().replace(/[&()]/g, '').replace(/\s+/g, '')
    if (normalizedTag.includes(catNormalized) || catNormalized.includes(normalizedTag)) {
      return category.toLowerCase().trim()
    }
  }
  const mappings = {
    vastu: 'home & vastu',
    relationship: 'love & relationships',
    marriage: 'marriage & match making',
    career: 'career & job',
    business: 'business & money',
    health: 'health & well-being',
    sleep: 'sleep & mental peace',
    spiritual: 'spiritual growth',
    prediction: 'daily / monthly predictions',
    astrology: 'astrology basics',
    planet: 'planets & grahas',
    house: 'houses (bhavas)',
    yoga: 'yogas & doshas',
    remedy: 'remedies & upay',
    dasha: 'dasha & transits',
    muhurat: 'muhurat & auspicious time',
    panchang: 'panchang',
    festival: 'festivals & rituals',
  }
  for (const [key, category] of Object.entries(mappings)) {
    if (normalizedTag.includes(key)) return category
  }
  return normalizedTag
}

export default async function ZodiacTodayPage({ searchParams }) {
  const allBlogs = await getPublishedBlogsAutoGenerated()
  const params = await searchParams

  let categoryFilter = 'all'
  if (params?.category) {
    try {
      categoryFilter = decodeURIComponent(params.category).toLowerCase().trim()
    } catch (e) {
      categoryFilter = params.category?.toLowerCase?.()?.trim() ?? 'all'
    }
  }

  const blogs =
    categoryFilter === 'all'
      ? allBlogs
      : allBlogs.filter((blog) => {
          if (!blog.tags || !Array.isArray(blog.tags)) return false
          return blog.tags.some((tag) => mapTagToCategory(tag) === categoryFilter)
        })

  return (
    <>
      <script
        dangerouslySetInnerHTML={{
          __html: `
(function() {
  const style = document.createElement('style');
  style.id = 'emergency-text-fix';
  style.textContent = \`
    html, body, * { text-align: left !important; text-justify: none !important; word-spacing: 0 !important; letter-spacing: 0 !important; text-align-last: left !important; }
    .blog-hero, .blog-hero * { text-align: center !important; text-align-last: center !important; }
  \`;
  document.head.insertBefore(style, document.head.firstChild);
})();
`,
        }}
      />
      <style
        dangerouslySetInnerHTML={{
          __html: `
html, body { text-align: left !important; text-justify: none !important; word-spacing: 0 !important; letter-spacing: 0 !important; }
.blog-listing-page, .blog-listing-page * { text-align: left !important; text-align-last: left !important; word-spacing: 0px !important; letter-spacing: 0px !important; hyphens: none !important; }
.blog-listing-page .blog-hero, .blog-listing-page .blog-hero * { text-align: center !important; text-align-last: center !important; }
.blog-listing-page .blog-meta-author { text-align: right !important; text-align-last: right !important; }
`,
        }}
      />

      <div className="blog-listing-page" key={categoryFilter}>
        <div className="blog-hero" style={{ paddingTop: '0.25rem', marginTop: '0.01rem' }}>
          <h1 className="title mx-auto flex align-center justify-center font-[700]">Zodiac News</h1>
          <p className="subtitle">
            Daily zodiac and astrology insights — predictions, transits, and cosmic updates
          </p>
        </div>

        <Suspense fallback={<div className="blog-filters"><div className="blog-filter-btn">Loading...</div></div>}>
          <BlogFilters blogs={allBlogs} basePath="/zodiac-today" />
        </Suspense>

        <div className="blog-container">
          {blogs.length === 0 ? (
            <div className="empty-state">
              <svg className="empty-icon" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253" />
              </svg>
              <h2 className="empty-title">No Zodiac News yet</h2>
              <p className="empty-text">Check back soon for new Zodiac News articles!</p>
            </div>
          ) : (
            <>
              <div className="blog-grid">
                {blogs.map((blog) => {
                  const excerpt =
                    blog.metaDescription ||
                    blog.excerpt ||
                    generateExcerpt(blog.content || '', 100)
                  const publishedDate = blog.publishedAt
                    ? new Date(blog.publishedAt).toLocaleDateString('en-US', {
                        year: 'numeric',
                        month: 'short',
                        day: 'numeric',
                      })
                    : ''
                  const primaryCategory = blog.tags?.length ? blog.tags[0] : 'Article'

                  return (
                    <div key={blog.id} className="blog-card-wrapper">
                      <a href={`/zodiac-today/${blog.slug}`} className="blog-card">
                        {blog.featuredImage && (
                          <div className="blog-image">
                            <Image
                              src={getOptimizedImageUrl(blog.featuredImage, 'mobile')}
                              alt={blog.title}
                              fill
                              className="object-cover"
                              sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
                            />
                            <span className="blog-category-overlay">{primaryCategory}</span>
                          </div>
                        )}
                        <div className="blog-content">
                          <div className="blog-meta">
                            <span className="blog-meta-date">{publishedDate}</span>
                            {blog.author && (
                              <span className="blog-meta-author">by {blog.author}</span>
                            )}
                          </div>
                          <h2 className="blog-title">{blog.title}</h2>
                          {excerpt && <p className="blog-excerpt">{excerpt}</p>}
                        </div>
                      </a>
                    </div>
                  )
                })}
              </div>
              <BlogListClient initialBlogs={blogs} autoGeneratedOnly />
            </>
          )}
        </div>

        <BlogFloatingCTA />
        <BlogTextFixer />
        <BackButtonHandler />

        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              '@context': 'https://schema.org',
              '@type': 'CollectionPage',
              name: 'Zodiac News | NiraLive Astro',
              description: 'AI-generated zodiac and astrology articles: daily predictions and cosmic updates',
              url: `${SITE_URL}/zodiac-today`,
              publisher: {
                '@type': 'Organization',
                name: 'NiraLive Astro',
                url: SITE_URL,
                logo: { '@type': 'ImageObject', url: `${SITE_URL}/icon-512x512.png` },
              },
              mainEntity: {
                '@type': 'ItemList',
                numberOfItems: blogs.length,
                itemListElement: blogs.slice(0, 10).map((blog, index) => ({
                  '@type': 'ListItem',
                  position: index + 1,
                  item: {
                    '@type': 'BlogPosting',
                    headline: blog.title,
                    description: blog.metaDescription || generateExcerpt(blog.content || '', 160),
                    url: `${SITE_URL}/zodiac-today/${blog.slug}`,
                    datePublished: blog.publishedAt,
                    dateModified: blog.updatedAt || blog.publishedAt,
                    image: blog.featuredImage || `${SITE_URL}/og-image.png`,
                    author: { '@type': 'Organization', name: blog.author || 'NiraLive Astro' },
                  },
                })),
              },
            }),
          }}
        />

        <PageSEO
          pageType="blog"
          faqs={[
            {
              question: 'What is Zodiac News?',
              answer: 'Zodiac News is our collection of AI-generated astrology and zodiac articles: daily predictions, planetary transits, and Vedic insights, updated regularly for fresh cosmic guidance.',
            },
            {
              question: 'How often is Zodiac News updated?',
              answer: 'We add new AI-generated zodiac and astrology articles on a regular schedule. Check back often for the latest zodiac news and cosmic updates.',
            },
            {
              question: 'Is Zodiac News different from the main blog?',
              answer: 'Yes. Zodiac News shows only our AI-generated astrology articles. For expert-written, human-authored articles, visit our main Astrology Blog.',
            },
          ]}
        />
      </div>
    </>
  )
}
